subpool:
  sublibrary_1:
    count: 13000
    i7_subpool_barcode: CAGATC
    i5_subpool_barcode: CAGATC
    long_read:
      platform: ONT PromethION
        seqspec: igvf_003/promethion/seqspec.yml
        run:
          1:
            fastqs:
              - igvf_003/nanopore/igvf003_13A_lig-ss_1.fastq.gz
              - igvf_003/nanopore/igvf003_13A_lig-ss_2.fastq.gz
      platform: ONT MinION
        seqspec: igvf_003/minion/seqspec.yml
        run:
          1:
            fastqs:
              - igvf_003/nanopore/minion/igvf003_13A_lig-ss_1.fastq.gz
              - igvf_003/nanopore/minion/igvf003_13A_lig-ss_2.fastq.gz
      short_read:

  sublibrary_1:
    count: 13000
