subpools:
  1:
    count: 13000
    i7_subpool_barcode: CAGATC
    i5_subpool_barcode: CAGATC
    selection: EX
    long_read:
      ONT PromethION:
        seqspec: igvf_003/promethion/seqspec.yml
        runs:
          1:
            fastqs:
              - igvf_003/nanopore/igvf003_13A_lig-ss_1.fastq.gz
              - igvf_003/nanopore/igvf003_13A_lig-ss_2.fastq.gz
      ONT MinION:
        seqspec: igvf_003/minion/seqspec.yml
        runs:
          1:
            fastqs:
              - igvf_003/nanopore/minion/igvf003_13A_lig-ss_1.fastq.gz
              - igvf_003/nanopore/minion/igvf003_13A_lig-ss_2.fastq.gz
    short_read:
      Illumina NextSeq 2000:
        seqspec: igvf_003/nextseq/seqspec.yaml
        runs:
          1:
            fastqs:
              - igvf_003/nextseq/003_13A_R1.fastq.gz
              - igvf_003/nextseq/003_13A_R2.fastq.gz
