ref:
  bc1_map: /share/crsp/lab/seyedam/share/igvf_splitseq/ref/r1_RT_replace.txt
  barcodes: /share/crsp/lab/seyedam/share/igvf_splitseq/ref/r1r2r3.txt
  t2g: /share/crsp/lab/seyedam/share/igvf_splitseq/ref/c57bl6j.t2g
  ind: /share/crsp/lab/seyedam/share/igvf_splitseq/ref/c57bl6j.idx
  c1: /share/crsp/lab/seyedam/share/igvf_splitseq/ref/c57bl6j.c1
  c2: /share/crsp/lab/seyedam/share/igvf_splitseq/ref/c57bl6j.c2

raw:
  # fastq: fastq/{plate}_{subpool}_{lane}_{read}_001.fastq.gz
  r1_fastq: fastq/{plate}_{subpool}_{lane}_R1_001.fastq.gz
  r2_fastq: fastq/{plate}_{subpool}_{lane}_R2_001.fastq.gz

kallisto:
  cgb: kallisto/{plate}_{subpool}/counts_unfiltered_modified/cells_x_genes.barcodes.txt
  cggn: kallisto/{plate}_{subpool}/counts_unfiltered_modified/cells_x_genes.genes.names.txt
  cgg: kallisto/{plate}_{subpool}/counts_unfiltered_modified/cells_x_genes.genes.txt
  cgn: kallisto/{plate}_{subpool}/counts_unfiltered_modified/cells_x_genes.nucleus.mtx
  adata: kallisto/{plate}_{subpool}/counts_unfiltered_modified/adata.h5ad

filter:
  adata: filter/{plate}_{subpool}/raw_adata.h5ad
  sample_adata: filter/{plate}_{sample}/adata.h5ad

scrublet:
