ref:
  # TODO - what's going on here
  bc1_map: /share/crsp/lab/seyedam/share/igvf_splitseq/ref/r1_RT_replace.txt
  barcodes: /share/crsp/lab/seyedam/share/igvf_splitseq/ref/r1r2r3.txt

  annot_link: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M32/gencode.vM32.chr_patch_hapl_scaff.annotation.gtf.gz
  annot: ref/gencode.vM32.gtf.gz
  fa_link: https://hgdownload.soe.ucsc.edu/goldenPath/mm39/bigZips/mm39.fa.gz
  fa: ref/mm39.fa.gz

  kallisto:
    t2g: ref/kallisto/c57bl6j.t2g
    ind: ref/kallisto/c57bl6j.idx
    fa: ref/kallisto/c57bl6j.fa
    c1: /share/crsp/lab/seyedam/share/igvf_splitseq/ref/c57bl6j.c1
    c2: /share/crsp/lab/seyedam/share/igvf_splitseq/ref/c57bl6j.c2

raw:
  # fastq: fastq/{plate}_{subpool}_{lane}_{read}_001.fastq.gz
  r1_fastq: fastq/{plate}_{subpool}_{run}_{lane}_R1_001.fastq.gz
  r2_fastq: fastq/{plate}_{subpool}_{run}_{lane}_R2_001.fastq.gz

kallisto:
  cgb: kallisto/{plate}_{subpool}/counts_unfiltered_modified/cells_x_genes.barcodes.txt
  cggn: kallisto/{plate}_{subpool}/counts_unfiltered_modified/cells_x_genes.genes.names.txt
  cgg: kallisto/{plate}_{subpool}/counts_unfiltered_modified/cells_x_genes.genes.txt
  cgn: kallisto/{plate}_{subpool}/counts_unfiltered_modified/cells_x_genes.nucleus.mtx
  adata: kallisto/{plate}_{subpool}/counts_unfiltered_modified/adata.h5ad

filter:
  adata: filter/{plate}_{subpool}/raw_adata.h5ad

scrublet:
  # TODO sample will be combo of {tissue}_{genotype}_{sex}_{age}_{mouse_id}
  adata: scrublet/{plate}_{sample}_{subpool}/adata.h5ad
  scrub_adata: scrublet/{plate}_{sample}_{subpool}/scrubbed_adata.h5ad

tissue:
  adata: ./{tissue}/adata.h5ad
